//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public Nullable<int> EmpID { get; set; }
        public int AttendanceID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> CurrDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
