//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRequest
    {
        public int AttReqID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime ReqDate { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public Nullable<bool> ReqStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
